---
- name: Install chezmoi
  pacman:
      name: chezmoi
      state: present
  when: dotfiles is defined
  tags:
    - packages

- name: Clone user dotfiles
  command: chezmoi init {{dotfiles.url}}
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
