---
- name: Install hunspell
  pacman:
    name:
      - hunspell
      - hunspell-en_US
      - hunspell-it
    state: present
  tags:
    - hunspell

- name: Install aspell
  pacman:
    name:
      - aspell
      - aspell-en
      - aspell-it
    state: present
  tags:
    - aspell
